name: Build App release

on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/**'
    paths-ignore:
      - '**.md'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  ANDROID_SDK_ROOT: /usr/lib/android-sdk

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/init-gradle
      - name: Build
        run: ./gradlew :app:assembleRelease $gradleFlags
      - name: Generate build time report
        uses: ./.github/actions/build-time-report
        with:
          file: app/build/reports/buildTimeTracker/build.csv
          output-file: buildTime.csv
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Upload time report
        uses: actions/upload-artifact@v4
        with:
          name: buildTime.csv
          path: buildTime.csv

  sign-app:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - uses: actions/download-artifact@v4
        with:
          name: app-unsigned
      - name: Install android cli tools
        shell: bash
        run: |
          set -e
          sudo mkdir -p $ANDROID_SDK_ROOT
          cd $ANDROID_SDK_ROOT
          sudo curl https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip -o android-tools.zip
          sudo unzip android-tools.zip
          sudo bash -c "yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses"
          sudo $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "build-tools;35.0.0"
      - name: Zipalign apk
        shell: bash
        run: |
          set -e
          $ANDROID_SDK_ROOT/build-tools/35.0.0/zipalign -v -p 4 app-release-unsigned.apk app-aligned.apk
      - name: Sign apk
        shell: bash
        run: |
          set -e
          echo ${{ secrets.JKS }} | base64 -d > release.jks
          $ANDROID_SDK_ROOT/build-tools/35.0.0/apksigner sign --ks release.jks --in app-aligned.apk --out app-signed.apk --key-pass pass:${{ secrets.JKS_KEY_PASS }} --ks-pass pass:${{ secrets.JKS_KS_PASS }} --ks-key-alias ${{ secrets.JKS_ALIAS }}
      - name: Verify signature
        shell: bash
        run: |
          set -e
          $ANDROID_SDK_ROOT/build-tools/35.0.0/apksigner verify app-signed.apk
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-signed
          path: app-signed.apk

  report-telegram:
    runs-on: ubuntu-latest
    needs: sign-app
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download apk
        uses: actions/download-artifact@v4
        with:
          name: app-signed
      - name: Report signed file
        uses: ./.github/actions/send-file-tg
        with:
          tg-token: ${{ secrets.TG_TOKEN }}
          tg-chat: ${{ secrets.TG_CHAT }}
          file: app-signed.apk
          text: "[Signed App for release ${{ github.head_ref }}](https://github.com/AlexeyPanchenko/shmr25_tmp/actions/runs/${{ github.run_id }})"